CE103 Algorithms and Programming I HW5: ce103_hw5_snake_test.UnitTest1 Class Reference
ce103_hw5_snake_test.UnitTest1 Class Reference
Public Member Functions
void collisionDetection_test_1 ()
void collisionDetection_test_2 ()
void collisionDetection_test_3 ()
void Eatfood_test_1 ()
void Eatfood_test_2 ()
void Eatfood_test_3 ()
void collisionSnake_test_1 ()
void collisionSnake_test_2 ()
void collisionSnake_test_3 ()
Member Function Documentation
collisionDetection_test_1()
void ce103_hw5_snake_test.UnitTest1.collisionDetection_test_1 () inline
References ce103_hw5_snake_dll.Class1.collisionDetection().
collisionDetection_test_2()
void ce103_hw5_snake_test.UnitTest1.collisionDetection_test_2 () inline
References ce103_hw5_snake_dll.Class1.collisionDetection().
collisionDetection_test_3()
void ce103_hw5_snake_test.UnitTest1.collisionDetection_test_3 () inline
References ce103_hw5_snake_dll.Class1.collisionDetection().
collisionSnake_test_1()
void ce103_hw5_snake_test.UnitTest1.collisionSnake_test_1 () inline
References ce103_hw5_snake_dll.Class1.collisionDetection().
collisionSnake_test_2()
void ce103_hw5_snake_test.UnitTest1.collisionSnake_test_2 () inline
References ce103_hw5_snake_dll.Class1.collisionDetection().
collisionSnake_test_3()
void ce103_hw5_snake_test.UnitTest1.collisionSnake_test_3 () inline
References ce103_hw5_snake_dll.Class1.collisionDetection().
Eatfood_test_1()
void ce103_hw5_snake_test.UnitTest1.Eatfood_test_1 () inline
References ce103_hw5_snake_dll.Class1.eatFood().
Eatfood_test_2()
void ce103_hw5_snake_test.UnitTest1.Eatfood_test_2 () inline
References ce103_hw5_snake_dll.Class1.eatFood().
Eatfood_test_3()
void ce103_hw5_snake_test.UnitTest1.Eatfood_test_3 () inline
References ce103_hw5_snake_dll.Class1.eatFood().
The documentation for this class was generated from the following file:
C:/Users/Ramazan Serhat UYGUN/Desktop/b/ce103-hw5-Haluk-KURTULUS/ce103-hw5-snake-test/UnitTest1.cs